// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXtrCt5_DDBbK0oDq1974SKn_lMCyas30',
    appId: '1:587035188193:web:5935633653acc1335410a0',
    messagingSenderId: '587035188193',
    projectId: 'project-app-b61df',
    authDomain: 'project-app-b61df.firebaseapp.com',
    storageBucket: 'project-app-b61df.appspot.com',
    measurementId: 'G-ZT9HHEJ5CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtCTrwWa0tGD9dKYFzRqvN5F9U9_1i1vc',
    appId: '1:587035188193:android:5c22237693d21d525410a0',
    messagingSenderId: '587035188193',
    projectId: 'project-app-b61df',
    storageBucket: 'project-app-b61df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1q6S1CfmO4nbJL0IOkPYlSGsOyVM4dDw',
    appId: '1:587035188193:ios:2b5c9ca4ec672f1c5410a0',
    messagingSenderId: '587035188193',
    projectId: 'project-app-b61df',
    storageBucket: 'project-app-b61df.appspot.com',
    iosClientId: '587035188193-7j063aemgbg78uqs5qt74ofcuafbtpmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1q6S1CfmO4nbJL0IOkPYlSGsOyVM4dDw',
    appId: '1:587035188193:ios:e9ed4d135fa450345410a0',
    messagingSenderId: '587035188193',
    projectId: 'project-app-b61df',
    storageBucket: 'project-app-b61df.appspot.com',
    iosClientId: '587035188193-4ffje492s1o8m2diaiofhm6p0fqfb2pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectShop.RunnerTests',
  );
}
